# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            The Rhythm of Life
email:            your-email@domain.com
description:      This blog charts my adventures playing and recording drums in my garden studio.
baseurl:          '/midan' # The subpath of your site, e.g. /blog
url:              'http://therhythmof.life' # The base hostname & protocol for your site
github_username:  paul66
twitter_username: paul66

markdown:  kramdown
permalink: pretty
paginate:  12
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  paul:
    name:             Paul Austin
    bio:              I practice, play and record drums in my garden studion.
    gravatar:         https://s.gravatar.com/avatar/75a38f2a6e4e83db1984439e3b500a46?s=150
    email:            
    website:          http://therhythmof.life
    github_username:  paul66
    twitter_username: paul66